### ISSUE TITLE
symbols ' and "

### ISSUE THREAD

**Issue by dni** [Xiphe/Password-Generator-for-zsh#1]
Hi!

Im using your plugin a lot and i like it, the only problem i have is, i keep on running into quotes errors in some cases (like mysql). i would love to have symbol pw's without quotes.

i was wondering if you could implement some kind of symbol-exclude flag where i can exclude the quotes, or some a symbol flag where you can pass your own symbols.

maybe even considering removing quotes from symbols list, because it can lead to some escaping errors in some cases like building a sql query?

bg dni

**Comment by Xiphe** [comment]
Added a new source `S` for symbols without quotes `pw_gen -s=aAnS` should behave similar to the default but without quotes

Glad you like the tool :)
